# Project information
site_name: 'Pandemia management'
site_description: 'Mobile application for pandemia management'
site_author: 'Jesus Ruiz'
site_url: 'https://hesusruiz.github.io/anti-pandemia/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2025 Jesus Ruiz'

docs_dir: docs_src
site_dir: docs
nav:
- Home: index.md
- Credentials:
  - Issuing credentials: issuing_credentials.md
  - Verifying credentials: verify_credentials.md
- Onboarding:
  - Natural persons: onboarding/natural_persons.md
  - Entities: onboarding/entities.md
- Types of Credentials:
  - Third-party attestations: attestations/normal_attestations.md
  - Self-attestations: attestations/self-attestations.md

# Configuration
theme:
    name: 'readthedocs'
    custom_dir: custom_theme/

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true

# Repository
# repo_name: 'hesusruiz/anti-pandemia'
repo_url: 'https://github.com/hesusruiz/anti-pandemia'

# Copyright
copyright: '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Jesus Ruiz</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons CC BY-SA 4.0 License</a>.'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/hesusruiz'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jesus-ruiz-martinez'


